# window border
window.active.border.color: {{primary}}
window.inactive.border.color: {{secondary}}

# ToggleKeybinds status indicator
window.active.indicator.toggled-keybind.color: {{error}}

# window titlebar background
window.active.title.bg.color: {{primary}}
window.inactive.title.bg.color: {{secondary}}

window.active.label.text.color: {{onPrimary}}
window.inactive.label.text.color: {{onSecondary}}
window.label.text.justify: center

# window button hover overlay
window.button.hover.bg.color: {{hover}}

# window buttons
window.active.button.unpressed.image.color: {{onPrimary}}
window.inactive.button.unpressed.image.color: {{onPrimary}}

# menu
menu.border.color: {{onPrimary}}
menu.items.bg.color: {{primary}}
menu.items.text.color: {{onPrimary}}
menu.items.active.bg.color: {{secondary}}
menu.items.active.text.color: {{onSecondary}}
menu.separator.color: {{onPrimary}}
menu.title.bg.color: {{primary}}
menu.title.text.color: {{onPrimary}}

# on screen display (window-cycle dialog)
osd.bg.color: {{primary}}
osd.border.color: {{onPrimary}}
osd.label.text.color: {{onPrimary}}
osd.window-switcher.preview.border.color: {{outline}}
