-- Generated by Quickshell Settings. Edit presets in ~/.config/quickshell/Config/Settings.qml.

return {
    -- Interruptor de la plantilla: conf/animations.lua aplica las
    -- animaciones personalizadas solo si esto es true; en false
    -- Hyprland se queda con sus animaciones por defecto.
    animations = true,

    accent   = "rgba(70c8ffee)",
    accent2  = "rgba(a1a8ffee)",
    inactive = "rgba(1e2427cc)",
    shadow   = "rgba(05080aee)",
    locked   = "rgba(df758eee)",

    active_border = { colors = { "rgba(70c8ffee)", "rgba(a1a8ffee)" }, angle = 45 },
    inactive_border = "rgba(1e2427cc)",

    group_active_border = "rgba(a1a8ffee)",
    group_inactive_border = "rgba(1e2427cc)",
    group_locked_active_border = "rgba(df758eee)",
    group_locked_inactive_border = "rgba(1e2427cc)",

    groupbar_active = "rgba(a1a8ffee)",
    groupbar_inactive = "rgba(1e2427cc)",
    groupbar_locked_active = "rgba(df758eee)",
    groupbar_locked_inactive = "rgba(1e2427cc)",
}
