-- Generated by Quickshell Settings. Edit presets in ~/.config/quickshell/Config/Settings.qml.

return {
    accent   = "rgba(0a84ffee)",
    accent2  = "rgba(64d2ffee)",
    inactive = "rgba(3a3f47cc)",
    shadow   = "rgba(000000ee)",

    active_border = { colors = { "rgba(0a84ffee)", "rgba(64d2ffee)" }, angle = 45 },
    inactive_border = "rgba(3a3f47cc)",
}
