-- Generated by Quickshell Settings. Edit presets in ~/.config/quickshell/Config/Settings.qml.

return {
    accent   = "rgba(798186ee)",
    accent2  = "rgba(caccccee)",
    inactive = "rgba(1e1e1ecc)",
    shadow   = "rgba(1a1a1aee)",

    active_border = { colors = { "rgba(798186ee)", "rgba(caccccee)" }, angle = 45 },
    inactive_border = "rgba(1e1e1ecc)",
}
