# Quickshell Theme for Mango
# Generated automatically by Quickshell

shadowscolor = 0x{{shadowStripped}}ff
rootcolor = 0x{{surfaceStripped}}ff
bordercolor = 0x{{outlineStripped}}ff
dropcolor = 0x{{primaryStripped}}80
splitcolor = 0x{{tertiaryStripped}}ff
focuscolor = 0x{{primaryStripped}}ff
maximizescreencolor = 0x{{secondaryStripped}}ff
urgentcolor = 0x{{errorStripped}}ff
scratchpadcolor = 0x{{tertiaryStripped}}ff
globalcolor = 0x{{primaryContainerStripped}}ff
overlaycolor = 0x{{secondaryContainerStripped}}ff
jump_label_decorate_fg_color = 0x{{onSurfaceStripped}}ff
jump_label_decorate_bg_color = 0x{{surfaceContainerHighStripped}}ff
jump_label_decorate_focus_fg_color = 0x{{onPrimaryStripped}}ff
jump_label_decorate_focus_bg_color = 0x{{primaryStripped}}ff
jump_label_decorate_border_color = 0x{{outlineStripped}}ff
group_bar_decorate_fg_color = 0x{{onSurfaceStripped}}ff
group_bar_decorate_bg_color = 0x{{surfaceContainerHighStripped}}ff
group_bar_decorate_focus_fg_color = 0x{{onPrimaryStripped}}ff
group_bar_decorate_focus_bg_color = 0x{{primaryStripped}}ff
group_bar_decorate_border_color = 0x{{outlineStripped}}ff
